#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

libs='../../libraries'
apps='..'

wmake $targetType "$libs/sigmoidFunction"
wmake $targetType "$libs/gasMetalThermalProperties"
wmake $targetType "$libs/laserHeatSource"
wmake $targetType quiescentGasMetalMixture
wmake $targetType volumetricLaserHeatSources
wmake $targetType

#------------------------------------------------------------------------------
