#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

apps='..'

wmake -a $targetType "$apps/stereolithography"
wmake $targetType

#------------------------------------------------------------------------------
