#!/bin/bash -e

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

if [[ "$1" == "-parallel" ]]; then
    runApplication blockMesh
    runApplication setFields
    runApplication decomposePar
    runParallel $application 4
    runApplication reconstructPar
else
    runApplication blockMesh
    runApplication setFields
    runApplication generatePowderBed alpha.metal
    runApplication $application
fi
