#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
cp 0/alpha.metal.orig 0/alpha.metal
runApplication setFields
runApplication generatePowderBed alpha.metal

if [[ "$1" == "-parallel" ]]; then
    runApplication decomposePar
    runParallel $application
    # Mesh reconstruction is not needed when a dynamic mesh is used
    # Use "Decomposed Case" in Paraview instead
    meshType="$(foamDictionary -entry dynamicFvMesh -value constant/dynamicMeshDict)"
    if [[ "$meshType" == staticFvMesh ]]; then
        runApplication reconstructPar
    fi
else
    runApplication $application
fi

runApplication ./plot_A.sh -eps -min=0.3 -max=0.9

root_dir="$(pwd | sed 's_/run/.*_/run_g')/.."
dir=rayTracing
if [[ -d "$dir" ]]; then
    "$root_dir/tools/obj2vtkseries.py" "$dir" > "$dir"/"$dir".vtk.series
    run() { runApplication "$@"; }
    for obj in $(find "$dir" -name '*.obj'); do
        vtk="${obj%obj}vtk"
        [[ -f "$vtk" ]] && continue
        run objToVTK "$obj" "$vtk"
        run() { "$@" >> log.objToVTK; }
    done
fi
echo "All is done!"
