#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

[ $# -ne 2 ] && { echo "Usage: ./Allrun <case> <kn>"; exit 1; }
case=$1
kn=$2

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

proj=$(ls *.geo | sed 's/\..*//')

sed -i~ -E "18s/[[:digit:]e.+-]+/$kn/" constant/nondimensionalProperties
cp -r 0.$case/ 0/

runApplication gmsh -3 $proj.geo
runApplication gmshToFoam $proj.msh
runApplication ./updatePolyMesh.sh
if ! test -f outputFile.stl; then
    runApplication foamToSurface -latestTime outputFile.stl
fi
runApplication topoSet
runApplication setsToZones

runApplication snitSimpleFoam
if test -f 0.$case/T && ! test -f log.snitSimpleFoam2; then
    last=$(foamListTimes | tail -1)
    echo "copy files from 0.$case/ to $last/"
    cp 0.$case/{T,U,curvature} $last/
    runApplication snitSimpleFoam2
fi

#runApplication wallSnitHeatFlux
#runApplication wallSnitForces
#runApplication sample
#runApplication calcGradients -fields '(T0)'

runApplication calcGradients -latestTime -fields '(T0 T)'
runApplication wallSnitDerivatives -latestTime
runApplication foamToVTK -latestTime
last=$(foamListTimes | tail -1)
$HOME/latex/science/7_snit_flows/elliptic/knudsen_layer_correction.py VTK/snit_solution_$last.vtk $proj.vtk $kn

echo ok

