#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

[ $# -ne 2 ] && { echo "Usage: ./Allrun <case> <kn>"; exit 1; }
case=$1
kn=$2

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

proj=$(ls *.geo | sed 's/\..*//')

sed -i~ -E "18s/[[:digit:]e.+-]+/$kn/" constant/nondimensionalProperties
cp -r 0.$case/ 0/

runApplication gmsh -3 $proj.geo
runApplication gmshToFoam $proj.msh
./updatePolyMesh.sh
if ! test -f outputFile.stl; then
    runApplication foamToSurface -latestTime outputFile.stl
fi
runApplication topoSet
runApplication setsToZones

runApplication snitSimpleFoam
if test -f 0.$case/T; then
    last=$(foamListTimes | tail -1)
    cp 0.$case/{T,U} $last/
    runApplication snitSimpleFoam2
fi

./Allrun2
last=$(foamListTimes | tail -1)
$HOME/latex/science/7_snit_flows/elliptic/knudsen_layer_correction.py VTK/snit_solution_$last.vtk $proj.vtk $kn
echo ok

