#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
restore0Dir
runApplication setFields

if [[ "$1" == "-parallel" ]]; then
    runApplication decomposePar
    runParallel $application
    runApplication reconstructPar
else
    runApplication $application
fi

# ----------------------------------------------------------------- end-of-file
