FROM openfoamplus/of_v2012_centos73:release

# boost-devel is used to build source-highlight from source
RUN yum install -y epel-release \
 && yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo \
 && yum install -y ack colordiff gdb git less mlocate boost-devel vim ripgrep \
 && yum clean all \
 && rm -rf /var/lib/apt/lists/*

# install vim-pathogen to colorizing OpenFOAM files
RUN curl https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim \
    > /usr/share/vim/vimfiles/autoload/pathogen.vim

# install source-highlight for colorize less
ARG source_highlight="source-highlight-3.1.8"
RUN curl ftp://ftp.gnu.org/gnu/src-highlite/"$source_highlight".tar.gz | tar xz \
 && cd "$source_highlight" \
 && ./configure && make -j && make install \
 && cd .. && rm -r "$source_highlight"

# activate OpenFOAM at each run
RUN echo openfoam > /etc/sysconfig/openfoam-selector

# download the missed OpenFOAM source files
ARG ofvers=v2012
#ADD OpenFOAM-$ofvers.tgz /
#RUN : \
RUN curl -SL https://sourceforge.net/projects/openfoam/files/$ofvers/OpenFOAM-$ofvers.tgz | tar xz \
 && cd OpenFOAM-$ofvers && mv applications src wmake /usr/lib/openfoam/openfoam/ \
 && source /etc/profile.d/openfoam-selector.sh \
 && cd /usr/lib/openfoam/openfoam/wmake/src && ./Allmake \
 && cd /usr/lib/openfoam/openfoam && wmakeLnIncludeAll \
 && rm -r /OpenFOAM-$ofvers

# update a database for mlocate
RUN updatedb
