#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

tmp=dynamicCode
if [[ "$1" != "-all" && -d $tmp ]]; then
    mv $tmp $tmp~
    echo "Save $tmp"
fi
cleanCase0
if [[ "$1" != "-all" && -d $tmp~ ]]; then
    mv $tmp~ $tmp
fi

# ----------------------------------------------------------------- end-of-file
