#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
restore0Dir
runApplication setFields

runApplication `getApplication`

runApplication postProcess -func singleGraph -latestTime

# ----------------------------------------------------------------- end-of-file
