#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
restore0Dir

if [[ "$1" == "-ZND" ]]; then
    runApplication setZNDsolution
else
    runApplication setFields
fi

runApplication `getApplication`

runApplication postProcess -func singleGraph -latestTime

# ----------------------------------------------------------------- end-of-file
