#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

[ $# -ne 2 ] && { echo "Usage: ./Allrun <case> <kn>"; exit 1; }
case=$1
kn=$2
rm log.calcGradients log.foamToVTK
runApplication calcGradients -fields '(T0)'
runApplication foamToVTK
patchIntegrate T0 top &> log.patchIntegrate.T0.top
patchIntegrate U1 top &> log.patchIntegrate.U1.top
patchIntegrate T0 bottom &> log.patchIntegrate.T0.bottom
patchIntegrate U1 bottom &> log.patchIntegrate.U1.bottom

# ----------------------------------------------------------------- end-of-file
