/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright held by original author(s)
     \\/     M anipulation  |
-------------------------------------------------------------------------------
                            | Copyright (C) 2022 Oleg Rogozin
-------------------------------------------------------------------------------
License
    This file is part of movingReferenceFrame.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::laboratoryFrame

Description
    Laboratory reference frame.

SourceFiles
    laboratoryFrame.C

\*---------------------------------------------------------------------------*/

#ifndef laboratoryFrame_H
#define laboratoryFrame_H

#include "movingReferenceFrame.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                         Class laboratoryFrame Declaration
\*---------------------------------------------------------------------------*/

class laboratoryFrame
:
    public movingReferenceFrame
{

    // Private Member Functions

        //- Evaluate the frame velocity
        void evaluate() final {}

public:

    //- Runtime type information
    TypeName("none");

    //- Constructor
    laboratoryFrame(const fvMesh& mesh);

    //- Destructor
    ~laboratoryFrame() final = default;

    // Member functions

        //- Is the reference frame moving?
        bool moving() const final
        {
            return false;
        }
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
