#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

proj=$(ls *.geo | sed 's/\..*//')

cleanCase
rm -rf $proj.msh $proj.vtk outputFile.stl constant/polyMesh *~
rm -rf 0/lagrangian 0/dsmcSigmaTcRMax 0/uniform
rm -rf processor*

# ----------------------------------------------------------------- end-of-file
