#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [[ "$1" == "-parallel" ]]; then
    runApplication blockMesh
    runApplication decomposePar
    runParallel -np 6 `getApplication`
    runApplication reconstructPar
    touch "$(basename `pwd`).foam"
    time DISPLAY=:1 ./make_video.py -x 1500 -y 600 -z 2.65 -f 12 *.foam
    ~/admin/converters/compress_videos.sh -a=4 video.avi
    awk '/^Time =.*/{a=$0} /^Tip p/{print a} /^Tip/{print}' log.`getApplication` > tip.txt
else
    runApplication blockMesh
    runApplication `getApplication`
fi

# ----------------------------------------------------------------- end-of-file
