#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication stereolithography
if [[ "$1" == "-bi" ]]; then
    runApplication setFields
fi
cp 0.orig/D 0/
runApplication `getApplication`

# ----------------------------------------------------------------- end-of-file
