#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

for arg; do case $arg in
    -parallel)          parallel=1;;
    -ZND)               ZND=1;;
    *)                  echo "Unknown option '$arg'."; exit 1;;
esac; done

runApplication blockMesh
restore0Dir

if [[ "$ZND" ]]; then
    runApplication setZNDsolution
else
    runApplication setFields
fi

if [[ "$parallel" ]]; then
    runApplication decomposePar

    if [[ "$ZND" ]]; then
        # Paraview failed to read the decomposed case without constant directory
        for dir in $(ls | grep ^processor); do (
            mkdir $dir/constant
            cd $dir/constant
            ln -sf ../0/polyMesh .
        ) done
    fi

    runParallel $application

    if [[ -z "$DISPLAY" ]]; then
        echo "Variable DISPLAY is not set. Skip rendering."
    else
        ndisplay="${DISPLAY#*:}"
        # If display is unavailable then run a VNC server at least, otherwise rendering failed
        if [[ ! -S "/tmp/.X11-unix/X$ndisplay" ]]; then
            vncserver "$DISPLAY"
        fi
        export DISPLAY
        touch "$(basename `pwd`).foam"
        runApplication ./make_video.py *.foam || true
        runApplication ~/admin/converters/compress_videos.sh -a=4 video.avi < /dev/null
    fi
else
    runApplication $application
fi

# ----------------------------------------------------------------- end-of-file
