#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
restore0Dir
runApplication setFields

if [[ "$1" == "-parallel" ]]; then
    runApplication decomposePar
    runParallel $application

    if [[ -z "$DISPLAY" ]]; then
        echo "Variable DISPLAY is not set. Skip rendering."
    else
        ndisplay="${DISPLAY#*:}"
        # If display is unavailable then run a VNC server at least, otherwise rendering failed
        if [[ ! -S "/tmp/.X11-unix/X$ndisplay" ]]; then
            vncserver "$DISPLAY"
        fi
        export DISPLAY
        touch "$(basename `pwd`).foam"
        runApplication ./make_video.py *.foam || true
        runApplication ~/admin/converters/compress_videos.sh -a=4 video.avi < /dev/null
    fi
else
    runApplication $application
fi

# ----------------------------------------------------------------- end-of-file
