#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

apps='..'

wmake $targetType "$apps/stereolithography/laserScanner"
wmake $targetType

#------------------------------------------------------------------------------
