#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

tmp=dynamicCode
mv $tmp $tmp~
cleanCase
mv $tmp~ $tmp

# ----------------------------------------------------------------- end-of-file
