#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

libs='../../libraries'
apps='..'

wmake $targetType "$libs/sigmoidFunction"
wmake $targetType "$libs/gasMetalThermalProperties"
wmake $targetType "$libs/movingReferenceFrame"
wmake $targetType "$libs/laserHeatSource"
wmake $targetType "$libs/trueArrhenius"
wmake $targetType "$libs/movingReferenceFrame"
wmake $targetType "$apps/generatePowderBed"
wmake $targetType incompressibleGasMetalMixture
wmake $targetType surfaceLaserHeatSources
wmake $targetType

#------------------------------------------------------------------------------
