#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

proj=$(ls *.geo | sed 's/\..*//')

cleanCase
rm -rf $proj.msh constant/polyMesh

# ----------------------------------------------------------------- end-of-file
