#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

proj=$(ls *.geo | sed 's/\..*//')

tmp=dynamicCode
mv $tmp $tmp~
cleanCase
mv $tmp~ $tmp
rm -rf $proj.msh constant/polyMesh 0 *~

# ----------------------------------------------------------------- end-of-file
