#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -f log.calcGradients log.foamToVTK
#runApplication calcGradients -fields '(T0)'
runApplication wallSnitDerivatives
runApplication foamToVTK
patchIntegrate T0 top &> log.patchIntegrate.T0.top
patchIntegrate U1 top &> log.patchIntegrate.U1.top
patchIntegrate T0 bottom &> log.patchIntegrate.T0.bottom
patchIntegrate U1 bottom &> log.patchIntegrate.U1.bottom

